//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRACOWNIK()
        {
            this.PROJEKT = new HashSet<PROJEKT>();
            this.PRZEDMIOT = new HashSet<PRZEDMIOT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DANE_OSOBOWE_ID { get; set; }
        public int SL_STANOWISKO_ID { get; set; }
    
        public virtual DANE_OSOBOWE DANE_OSOBOWE { get; set; }
        public virtual SL_STANOWISKO SL_STANOWISKO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJEKT> PROJEKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRZEDMIOT> PRZEDMIOT { get; set; }
    }
}
