//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PRZEDMIOT
    {
        public int ID { get; set; }
        public int STUDENT_ID { get; set; }
        public int PRZEDMIOT_ID { get; set; }
        public Nullable<decimal> OCENA { get; set; }
        public string OPIS { get; set; }
    
        public virtual PRZEDMIOT PRZEDMIOT { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
