//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DziennikASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.PROJEKT = new HashSet<PROJEKT>();
            this.STUDENT_PRZEDMIOT = new HashSet<STUDENT_PRZEDMIOT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DANE_OSOBOWE_ID { get; set; }
        public Nullable<int> GRUPA_ID { get; set; }
        public string NUMER_ALBUMU { get; set; }
    
        public virtual DANE_OSOBOWE DANE_OSOBOWE { get; set; }
        public virtual GRUPA GRUPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJEKT> PROJEKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PRZEDMIOT> STUDENT_PRZEDMIOT { get; set; }
    }
}
